// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whcvyzbphmjsrvcvizxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoY3Z5emJwaG1qc3J2Y3ZpenhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDYzOTcsImV4cCI6MjA3MTg4MjM5N30.esqCjHU8TB429vjkAkLeLWn7k2i4f4pCMIPSpsnVZyA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});